#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actor_MintUltraSkill_TimeDilation

#include "Basic.hpp"

#include "BP_TimeDilationVolumeActor_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Actor_MintUltraSkill_TimeDilation.Actor_MintUltraSkill_TimeDilation_C
// 0x0008 (0x0370 - 0x0368)
class AActor_MintUltraSkill_TimeDilation_C final : public ABP_TimeDilationVolumeActor_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Actor_MintUltraSkill_TimeDilation_C; // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Actor_MintUltraSkill_TimeDilation(int32 EntryPoint);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Actor_MintUltraSkill_TimeDilation_C">();
	}
	static class AActor_MintUltraSkill_TimeDilation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AActor_MintUltraSkill_TimeDilation_C>();
	}
};

}

