#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CanBreakPassiveEffectNS

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CanBreakPassiveEffectNS.BP_CanBreakPassiveEffectNS_C
// 0x0000 (0x0030 - 0x0030)
class UBP_CanBreakPassiveEffectNS_C final : public UNotifyState_CanBreakPassiveEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CanBreakPassiveEffectNS_C">();
	}
	static class UBP_CanBreakPassiveEffectNS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CanBreakPassiveEffectNS_C>();
	}
};

}

