#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameData

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameData.BP_GameData_C
// 0x0000 (0x1818 - 0x1818)
class UBP_GameData_C final : public UHTGameData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GameData_C">();
	}
	static class UBP_GameData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameData_C>();
	}
};

}

