#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HTCharacterLevelTransferState

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HTCharacterLevelTransferState.BP_HTCharacterLevelTransferState_C
// 0x0000 (0x01C0 - 0x01C0)
class UBP_HTCharacterLevelTransferState_C final : public UHTCharacterLevelTransferState
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HTCharacterLevelTransferState_C">();
	}
	static class UBP_HTCharacterLevelTransferState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HTCharacterLevelTransferState_C>();
	}
};

}

