#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_House_PBG

#include "Basic.hpp"

#include "BP_House_PBG_classes.hpp"
#include "BP_House_PBG_parameters.hpp"


namespace SDK
{

// Function BP_House_PBG.BP_House_PBG_C.Build
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::Build()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "Build");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.BuildProps
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::BuildProps()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "BuildProps");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.ClearEmptyISM
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::ClearEmptyISM()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "ClearEmptyISM");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.CreateRoofMesh
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::CreateRoofMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "CreateRoofMesh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.ExecuteUbergraph_BP_House_PBG
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_House_PBG_C::ExecuteUbergraph_BP_House_PBG(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "ExecuteUbergraph_BP_House_PBG");

	Params::BP_House_PBG_C_ExecuteUbergraph_BP_House_PBG Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_House_PBG.BP_House_PBG_C.MobileSetting
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::MobileSetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "MobileSetting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_House_PBG_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.Updata Build
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::Updata_Build()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "Updata Build");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_House_PBG.BP_House_PBG_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_House_PBG_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_House_PBG_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

