#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HTMassTrafficVehicleSpawnDataGenerator

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HTMassTrafficVehicleSpawnDataGenerator.BP_HTMassTrafficVehicleSpawnDataGenerator_C
// 0x0000 (0x0058 - 0x0058)
class UBP_HTMassTrafficVehicleSpawnDataGenerator_C final : public UHTMassTrafficVehicleSpawnDataGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HTMassTrafficVehicleSpawnDataGenerator_C">();
	}
	static class UBP_HTMassTrafficVehicleSpawnDataGenerator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HTMassTrafficVehicleSpawnDataGenerator_C>();
	}
};

}

