#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IdleStatePatrol_Base

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IdleStatePatrol_Base.BP_IdleStatePatrol_Base_C
// 0x0000 (0x0328 - 0x0328)
class UBP_IdleStatePatrol_Base_C : public UHTAIIdleState_Patrol
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IdleStatePatrol_Base_C">();
	}
	static class UBP_IdleStatePatrol_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IdleStatePatrol_Base_C>();
	}
};

}

