#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MyHTSelfieActivityVolume_s110619

#include "Basic.hpp"

#include "BP_MyHTSelfieActivityVolume_s110619_classes.hpp"
#include "BP_MyHTSelfieActivityVolume_s110619_parameters.hpp"


namespace SDK
{

// Function BP_MyHTSelfieActivityVolume_s110619.BP_MyHTSelfieActivityVolume_s110619_C.BPCanActiveFunc
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTPlayerState*                   PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_MyHTSelfieActivityVolume_s110619_C::BPCanActiveFunc(class AHTPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MyHTSelfieActivityVolume_s110619_C", "BPCanActiveFunc");

	Params::BP_MyHTSelfieActivityVolume_s110619_C_BPCanActiveFunc Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_MyHTSelfieActivityVolume_s110619.BP_MyHTSelfieActivityVolume_s110619_C.ExecuteUbergraph_BP_MyHTSelfieActivityVolume_s110619
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MyHTSelfieActivityVolume_s110619_C::ExecuteUbergraph_BP_MyHTSelfieActivityVolume_s110619(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MyHTSelfieActivityVolume_s110619_C", "ExecuteUbergraph_BP_MyHTSelfieActivityVolume_s110619");

	Params::BP_MyHTSelfieActivityVolume_s110619_C_ExecuteUbergraph_BP_MyHTSelfieActivityVolume_s110619 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MyHTSelfieActivityVolume_s110619.BP_MyHTSelfieActivityVolume_s110619_C.OnTakePhotoClickedEvent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSelfieCheckTargetState>  GainFlagActors                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_MyHTSelfieActivityVolume_s110619_C::OnTakePhotoClickedEvent(const TArray<struct FSelfieCheckTargetState>& GainFlagActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MyHTSelfieActivityVolume_s110619_C", "OnTakePhotoClickedEvent");

	Params::BP_MyHTSelfieActivityVolume_s110619_C_OnTakePhotoClickedEvent Parms{};

	Parms.GainFlagActors = std::move(GainFlagActors);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MyHTSelfieActivityVolume_s110619.BP_MyHTSelfieActivityVolume_s110619_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_MyHTSelfieActivityVolume_s110619_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MyHTSelfieActivityVolume_s110619_C", "ReceiveActorBeginOverlap");

	Params::BP_MyHTSelfieActivityVolume_s110619_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

