#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MassStreetLampSpawner

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MassStreetLampSpawner.BP_MassStreetLampSpawner_C
// 0x0000 (0x0418 - 0x0418)
class ABP_MassStreetLampSpawner_C final : public AMassStreetLampSpawner
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MassStreetLampSpawner_C">();
	}
	static class ABP_MassStreetLampSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MassStreetLampSpawner_C>();
	}
};

}

