#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_006_A

#include "Basic.hpp"

#include "BP_Anomaly_006_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_006_A.BP_NPC_006_A_C
// 0x0000 (0x20F0 - 0x20F0)
class ABP_NPC_006_A_C : public ABP_Anomaly_006_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NPC_006_A_C">();
	}
	static class ABP_NPC_006_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_006_A_C>();
	}
};

}

