#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Base

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_Base.BP_NPC_Base_C
// 0x0000 (0x20B0 - 0x20B0)
class ABP_NPC_Base_C : public AHTNPCCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NPC_Base_C">();
	}
	static class ABP_NPC_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Base_C>();
	}
};

}

