#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StoreBrandHeadLogoActor

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StoreBrandHeadLogoActor.BP_StoreBrandHeadLogoActor_C
// 0x0000 (0x0B60 - 0x0B60)
class ABP_StoreBrandHeadLogoActor_C : public AHTStoreBrandHeadLogoActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StoreBrandHeadLogoActor_C">();
	}
	static class ABP_StoreBrandHeadLogoActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StoreBrandHeadLogoActor_C>();
	}
};

}

