#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UHTGameplayCueManager

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UHTGameplayCueManager.BP_UHTGameplayCueManager_C
// 0x0000 (0x03D0 - 0x03D0)
class UBP_UHTGameplayCueManager_C final : public UHTGameplayCueManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UHTGameplayCueManager_C">();
	}
	static class UBP_UHTGameplayCueManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UHTGameplayCueManager_C>();
	}
};

}

