#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VehicleEffectComponent

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VehicleEffectComponent.BP_VehicleEffectComponent_C
// 0x0000 (0x06E8 - 0x06E8)
class UBP_VehicleEffectComponent_C final : public UHTVehicleEffectComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VehicleEffectComponent_C">();
	}
	static class UBP_VehicleEffectComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VehicleEffectComponent_C>();
	}
};

}

