#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPBubbleComponent

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPBubbleComponent.BPBubbleComponent_C
// 0x0000 (0x0840 - 0x0840)
class UBPBubbleComponent_C final : public UHTBubbleComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPBubbleComponent_C">();
	}
	static class UBPBubbleComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPBubbleComponent_C>();
	}
};

}

