#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_MiniMap_RadarContainer

#include "Basic.hpp"

#include "BPUI_MiniMap_RadarContainer_classes.hpp"
#include "BPUI_MiniMap_RadarContainer_parameters.hpp"


namespace SDK
{

// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.GetRadarStateChangeAnimValue
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  TimeCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMiniMapRadarStateChangeAnimState       AnimState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ValueRange                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  OutValue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Finished                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::GetRadarStateChangeAnimValue(double TimeCount, EMiniMapRadarStateChangeAnimState AnimState, const struct FVector2D& ValueRange, double* OutValue, bool* Finished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "GetRadarStateChangeAnimValue");

	Params::BPUI_MiniMap_RadarContainer_C_GetRadarStateChangeAnimValue Parms{};

	Parms.TimeCount = TimeCount;
	Parms.AnimState = AnimState;
	Parms.ValueRange = std::move(ValueRange);

	UObject::ProcessEvent(Func, &Parms);

	if (OutValue != nullptr)
		*OutValue = Parms.OutValue;

	if (Finished != nullptr)
		*Finished = Parms.Finished;
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.ExecuteUbergraph_BPUI_MiniMap_RadarContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::ExecuteUbergraph_BPUI_MiniMap_RadarContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "ExecuteUbergraph_BPUI_MiniMap_RadarContainer");

	Params::BPUI_MiniMap_RadarContainer_C_ExecuteUbergraph_BPUI_MiniMap_RadarContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_MiniMap_RadarContainer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_UpdateRadarStateChangeAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMiniMapRadarStateChangeAnimState       InRadarStateChangeAnimState                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TimeCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_UpdateRadarStateChangeAnim(EMiniMapRadarStateChangeAnimState InRadarStateChangeAnimState, float TimeCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_UpdateRadarStateChangeAnim");

	Params::BPUI_MiniMap_RadarContainer_C_BP_UpdateRadarStateChangeAnim Parms{};

	Parms.InRadarStateChangeAnimState = InRadarStateChangeAnimState;
	Parms.TimeCount = TimeCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_UpdateRadarColor
// (Event, Protected, BlueprintEvent)
// Parameters:
// EVisionRadarState                       InRadarState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMiniMapRadarStateChangeAnimState       InRadarStateChangeAnimState                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DistValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_UpdateRadarColor(EVisionRadarState InRadarState, EMiniMapRadarStateChangeAnimState InRadarStateChangeAnimState, float DistValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_UpdateRadarColor");

	Params::BPUI_MiniMap_RadarContainer_C_BP_UpdateRadarColor Parms{};

	Parms.InRadarState = InRadarState;
	Parms.InRadarStateChangeAnimState = InRadarStateChangeAnimState;
	Parms.DistValue = DistValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_OnUpdateRadarMaxDimensionAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMiniMapRadarMaxDimensionAnimState      InRadarMaxDimensionAnimState                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TimeCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_OnUpdateRadarMaxDimensionAnim(EMiniMapRadarMaxDimensionAnimState InRadarMaxDimensionAnimState, float TimeCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_OnUpdateRadarMaxDimensionAnim");

	Params::BPUI_MiniMap_RadarContainer_C_BP_OnUpdateRadarMaxDimensionAnim Parms{};

	Parms.InRadarMaxDimensionAnimState = InRadarMaxDimensionAnimState;
	Parms.TimeCount = TimeCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_OnStopRadarStateChangeAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMiniMapRadarStateChangeAnimState       AnimState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_OnStopRadarStateChangeAnim(EMiniMapRadarStateChangeAnimState AnimState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_OnStopRadarStateChangeAnim");

	Params::BPUI_MiniMap_RadarContainer_C_BP_OnStopRadarStateChangeAnim Parms{};

	Parms.AnimState = AnimState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_OnRefreshRadarRotate
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_OnRefreshRadarRotate(float Angle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_OnRefreshRadarRotate");

	Params::BPUI_MiniMap_RadarContainer_C_BP_OnRefreshRadarRotate Parms{};

	Parms.Angle = Angle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_OnPlayRadarStateChangeAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMiniMapRadarStateChangeAnimState       AnimState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_OnPlayRadarStateChangeAnim(EMiniMapRadarStateChangeAnimState AnimState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_OnPlayRadarStateChangeAnim");

	Params::BPUI_MiniMap_RadarContainer_C_BP_OnPlayRadarStateChangeAnim Parms{};

	Parms.AnimState = AnimState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_MiniMap_RadarContainer.BPUI_MiniMap_RadarContainer_C.BP_OnPlayRadarMaxDimensionAnim
// (Event, Protected, BlueprintEvent)
// Parameters:
// EMiniMapRadarMaxDimensionAnimState      InRadarMaxDimensionAnimState                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_MiniMap_RadarContainer_C::BP_OnPlayRadarMaxDimensionAnim(EMiniMapRadarMaxDimensionAnimState InRadarMaxDimensionAnimState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_MiniMap_RadarContainer_C", "BP_OnPlayRadarMaxDimensionAnim");

	Params::BPUI_MiniMap_RadarContainer_C_BP_OnPlayRadarMaxDimensionAnim Parms{};

	Parms.InRadarMaxDimensionAnimState = InRadarMaxDimensionAnimState;

	UObject::ProcessEvent(Func, &Parms);
}

}

