#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_RoleID

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_RoleID.BPUI_RoleID_C
// 0x0018 (0x0AA0 - 0x0A88)
class UBPUI_RoleID_C final : public UHTUIBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             RoleId;                                            // 0x0A90(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bShow;                                             // 0x0A98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInit;                                             // 0x0A99(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPUI_RoleID(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void UpdateRoleID();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPUI_RoleID_C">();
	}
	static class UBPUI_RoleID_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_RoleID_C>();
	}
};

}

