#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Player_Female_SkillDisplay1

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_Player_Female_SkillDisplay1.Buff_Player_Female_SkillDisplay1_C.ExecuteUbergraph_Buff_Player_Female_SkillDisplay1
// 0x0004 (0x0004 - 0x0000)
struct Buff_Player_Female_SkillDisplay1_C_ExecuteUbergraph_Buff_Player_Female_SkillDisplay1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

