#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Common_ClimbSprintState_Tag

#include "Basic.hpp"

#include "BuffBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_Common_ClimbSprintState_Tag.Buff_Common_ClimbSprintState_Tag_C
// 0x0000 (0x0C70 - 0x0C70)
class UBuff_Common_ClimbSprintState_Tag_C final : public UBuffBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_Common_ClimbSprintState_Tag_C">();
	}
	static class UBuff_Common_ClimbSprintState_Tag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_Common_ClimbSprintState_Tag_C>();
	}
};

}

