#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Sagiri003_Passive1

#include "Basic.hpp"

#include "Buff_Sagiri003_Passive1_classes.hpp"
#include "Buff_Sagiri003_Passive1_parameters.hpp"


namespace SDK
{

// Function Buff_Sagiri003_Passive1.Buff_Sagiri003_Passive1_C.ExecuteUbergraph_Buff_Sagiri003_Passive1
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBuff_Sagiri003_Passive1_C::ExecuteUbergraph_Buff_Sagiri003_Passive1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Sagiri003_Passive1_C", "ExecuteUbergraph_Buff_Sagiri003_Passive1");

	Params::Buff_Sagiri003_Passive1_C_ExecuteUbergraph_Buff_Sagiri003_Passive1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

