#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Lacrimosa004_Level5

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_Lacrimosa004_Level5.Buff_Lacrimosa004_Level5_C.ExecuteUbergraph_Buff_Lacrimosa004_Level5
// 0x0004 (0x0004 - 0x0000)
struct Buff_Lacrimosa004_Level5_C_ExecuteUbergraph_Buff_Lacrimosa004_Level5 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

