#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Fadia039_Passive1

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_Fadia039_Passive1.Buff_Fadia039_Passive1_C.ExecuteUbergraph_Buff_Fadia039_Passive1
// 0x0004 (0x0004 - 0x0000)
struct Buff_Fadia039_Passive1_C_ExecuteUbergraph_Buff_Fadia039_Passive1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

