#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_ExtremeEvade_Dir

#include "Basic.hpp"

#include "Buff_ExtremeEvade_Dir_classes.hpp"
#include "Buff_ExtremeEvade_Dir_parameters.hpp"


namespace SDK
{

// Function Buff_ExtremeEvade_Dir.Buff_ExtremeEvade_Dir_C.ExecuteUbergraph_Buff_ExtremeEvade_Dir
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBuff_ExtremeEvade_Dir_C::ExecuteUbergraph_Buff_ExtremeEvade_Dir(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_ExtremeEvade_Dir_C", "ExecuteUbergraph_Buff_ExtremeEvade_Dir");

	Params::Buff_ExtremeEvade_Dir_C_ExecuteUbergraph_Buff_ExtremeEvade_Dir Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

