#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_ExtemeEvde_AtkProperty

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_ExtemeEvde_AtkProperty.Buff_ExtemeEvde_AtkProperty_C.ExecuteUbergraph_Buff_ExtemeEvde_AtkProperty
// 0x0004 (0x0004 - 0x0000)
struct Buff_ExtemeEvde_AtkProperty_C_ExecuteUbergraph_Buff_ExtemeEvde_AtkProperty final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

