#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Tenacity_damage

#include "Basic.hpp"

#include "BuffBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_Tenacity_damage.Buff_Tenacity_damage_C
// 0x0000 (0x0C70 - 0x0C70)
class UBuff_Tenacity_damage_C final : public UBuffBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_Tenacity_damage_C">();
	}
	static class UBuff_Tenacity_damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_Tenacity_damage_C>();
	}
};

}

