#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Tenacity_ParticleEffect

#include "Basic.hpp"

#include "BuffBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_Tenacity_ParticleEffect.Buff_Tenacity_ParticleEffect_C
// 0x0000 (0x0C70 - 0x0C70)
class UBuff_Tenacity_ParticleEffect_C final : public UBuffBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_Tenacity_ParticleEffect_C">();
	}
	static class UBuff_Tenacity_ParticleEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_Tenacity_ParticleEffect_C>();
	}
};

}

