#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Fadia_ChangeState

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_Fadia_ChangeState.Buff_Fadia_ChangeState_C.ExecuteUbergraph_Buff_Fadia_ChangeState
// 0x0004 (0x0004 - 0x0000)
struct Buff_Fadia_ChangeState_C_ExecuteUbergraph_Buff_Fadia_ChangeState final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

