#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Fadia_ShareOutTeammatesDamage

#include "Basic.hpp"

#include "Buff_Fadia_ShareOutTeammatesDamage_classes.hpp"
#include "Buff_Fadia_ShareOutTeammatesDamage_parameters.hpp"


namespace SDK
{

// Function Buff_Fadia_ShareOutTeammatesDamage.Buff_Fadia_ShareOutTeammatesDamage_C.ExecuteUbergraph_Buff_Fadia_ShareOutTeammatesDamage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBuff_Fadia_ShareOutTeammatesDamage_C::ExecuteUbergraph_Buff_Fadia_ShareOutTeammatesDamage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Fadia_ShareOutTeammatesDamage_C", "ExecuteUbergraph_Buff_Fadia_ShareOutTeammatesDamage");

	Params::Buff_Fadia_ShareOutTeammatesDamage_C_ExecuteUbergraph_Buff_Fadia_ShareOutTeammatesDamage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

