#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_FadiaHit

#include "Basic.hpp"

#include "BP_CameraShake_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_FadiaHit.CameraShake_FadiaHit_C
// 0x0000 (0x01F0 - 0x01F0)
class UCameraShake_FadiaHit_C final : public UBP_CameraShake_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_FadiaHit_C">();
	}
	static class UCameraShake_FadiaHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_FadiaHit_C>();
	}
};

}

