#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cau_Fadia_Q_HighRecoverHP

#include "Basic.hpp"

#include "Cau_Fadia_Q_RecoverHP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cau_Fadia_Q_HighRecoverHP.Cau_Fadia_Q_HighRecoverHP_C
// 0x0000 (0x00B0 - 0x00B0)
class UCau_Fadia_Q_HighRecoverHP_C final : public UCau_Fadia_Q_RecoverHP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cau_Fadia_Q_HighRecoverHP_C">();
	}
	static class UCau_Fadia_Q_HighRecoverHP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCau_Fadia_Q_HighRecoverHP_C>();
	}
};

}

