#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Con_FemaleSkill_TargetLevel2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Con_FemaleSkill_TargetLevel2.Con_FemaleSkill_TargetLevel2_C
// 0x0008 (0x0038 - 0x0030)
class UCon_FemaleSkill_TargetLevel2_C final : public UHTGameplayEffectCustomApplicationRequirement
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Con_FemaleSkill_TargetLevel2(int32 EntryPoint);

	bool CanApplyGameplayEffectContent(class AActor* SourceActor, class AActor* TargetActor, class AActor* InstigatorActor, const class UGameplayEffect* GameplayEffect) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Con_FemaleSkill_TargetLevel2_C">();
	}
	static class UCon_FemaleSkill_TargetLevel2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCon_FemaleSkill_TargetLevel2_C>();
	}
};

}

