#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageRange_Female_Skill_Level1

#include "Basic.hpp"

#include "BP_PlayerType_DamageBoxBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DamageRange_Female_Skill_Level1.DamageRange_Female_Skill_Level1_C
// 0x0000 (0x0148 - 0x0148)
class UDamageRange_Female_Skill_Level1_C final : public UBP_PlayerType_DamageBoxBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DamageRange_Female_Skill_Level1_C">();
	}
	static class UDamageRange_Female_Skill_Level1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageRange_Female_Skill_Level1_C>();
	}
};

}

