#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataflowEnginePlugin

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class DataflowEnginePlugin.DataflowActor
// 0x0008 (0x02A8 - 0x02A0)
class ADataflowActor final : public AActor
{
public:
	class UDataflowComponent*                     DataflowComponent;                                 // 0x02A0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DataflowActor">();
	}
	static class ADataflowActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADataflowActor>();
	}
};

// Class DataflowEnginePlugin.DataflowComponent
// 0x0140 (0x0660 - 0x0520)
class UDataflowComponent final : public UPrimitiveComponent
{
public:
	uint8                                         Pad_4ED6[0x140];                                   // 0x0520(0x0140)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DataflowComponent">();
	}
	static class UDataflowComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDataflowComponent>();
	}
};

}

