#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FadiaHitBackMelee1

#include "Basic.hpp"

#include "SkillEffect_HitBack_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FadiaHitBackMelee1.FadiaHitBackMelee1_C
// 0x0000 (0x01D8 - 0x01D8)
class UFadiaHitBackMelee1_C final : public USkillEffect_HitBack_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FadiaHitBackMelee1_C">();
	}
	static class UFadiaHitBackMelee1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFadiaHitBackMelee1_C>();
	}
};

}

