#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FadiaHitBackUltraSkillMelee2

#include "Basic.hpp"

#include "SkillEffect_HitBack_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FadiaHitBackUltraSkillMelee2.FadiaHitBackUltraSkillMelee2_C
// 0x0000 (0x01D8 - 0x01D8)
class UFadiaHitBackUltraSkillMelee2_C final : public USkillEffect_HitBack_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FadiaHitBackUltraSkillMelee2_C">();
	}
	static class UFadiaHitBackUltraSkillMelee2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFadiaHitBackUltraSkillMelee2_C>();
	}
};

}

