#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FloatingActorFemaleUltraSkill

#include "Basic.hpp"

#include "BP_floatingEffectActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FloatingActorFemaleUltraSkill.FloatingActorFemaleUltraSkill_C
// 0x0000 (0x04B0 - 0x04B0)
class AFloatingActorFemaleUltraSkill_C final : public ABP_floatingEffectActor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FloatingActorFemaleUltraSkill_C">();
	}
	static class AFloatingActorFemaleUltraSkill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFloatingActorFemaleUltraSkill_C>();
	}
};

}

