#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FootIK_AnimLayer

#include "Basic.hpp"

#include "FootIK_AnimLayer_classes.hpp"
#include "FootIK_AnimLayer_parameters.hpp"


namespace SDK
{

// Function FootIK_AnimLayer.FootIK_AnimLayer_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UFootIK_AnimLayer_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FootIK_AnimLayer_C", "AnimGraph");

	Params::FootIK_AnimLayer_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function FootIK_AnimLayer.FootIK_AnimLayer_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFootIK_AnimLayer_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FootIK_AnimLayer_C", "BlueprintUpdateAnimation");

	Params::FootIK_AnimLayer_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FootIK_AnimLayer.FootIK_AnimLayer_C.ExecuteUbergraph_FootIK_AnimLayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFootIK_AnimLayer_C::ExecuteUbergraph_FootIK_AnimLayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FootIK_AnimLayer_C", "ExecuteUbergraph_FootIK_AnimLayer");

	Params::FootIK_AnimLayer_C_ExecuteUbergraph_FootIK_AnimLayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FootIK_AnimLayer.FootIK_AnimLayer_C.FootIKLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_FootIKLayer                                      (Parm, OutParm, NoDestructor)

void UFootIK_AnimLayer_C::FootIKLayer(const struct FPoseLink& InPose, struct FPoseLink* Param_FootIKLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FootIK_AnimLayer_C", "FootIKLayer");

	Params::FootIK_AnimLayer_C_FootIKLayer Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_FootIKLayer != nullptr)
		*Param_FootIKLayer = std::move(Parms.Param_FootIKLayer);
}

}

