#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Female_Skill

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_Female_Skill.GA_Female_Skill_C.ExecuteUbergraph_GA_Female_Skill
// 0x0004 (0x0004 - 0x0000)
struct GA_Female_Skill_C_ExecuteUbergraph_GA_Female_Skill final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

