#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_MeleeBase

#include "Basic.hpp"

#include "GA_MontageBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_MeleeBase.GA_MeleeBase_C
// 0x0000 (0x0A60 - 0x0A60)
class UGA_MeleeBase_C : public UGA_MontageBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_MeleeBase_C">();
	}
	static class UGA_MeleeBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_MeleeBase_C>();
	}
};

}

