#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_ActorReaction_1_1019_Damage

#include "Basic.hpp"

#include "GE_ActorReaction_1_1019_Damage_classes.hpp"
#include "GE_ActorReaction_1_1019_Damage_parameters.hpp"


namespace SDK
{

// Function GE_ActorReaction_1_1019_Damage.GE_ActorReaction_1_1019_Damage_C.ExecuteUbergraph_GE_ActorReaction_1_1019_Damage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGE_ActorReaction_1_1019_Damage_C::ExecuteUbergraph_GE_ActorReaction_1_1019_Damage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GE_ActorReaction_1_1019_Damage_C", "ExecuteUbergraph_GE_ActorReaction_1_1019_Damage");

	Params::GE_ActorReaction_1_1019_Damage_C_ExecuteUbergraph_GE_ActorReaction_1_1019_Damage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

