#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_DamageBase

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_DamageBase.GE_DamageBase_C
// 0x0000 (0x0C70 - 0x0C70)
class UGE_DamageBase_C : public UHTGamePlayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_DamageBase_C">();
	}
	static class UGE_DamageBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_DamageBase_C>();
	}
};

}

