#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Player_Skia_ShadowAtk_Damage

#include "Basic.hpp"


namespace SDK::Params
{

// Function GE_Player_Skia_ShadowAtk_Damage.GE_Player_Skia_ShadowAtk_Damage_C.ExecuteUbergraph_GE_Player_Skia_ShadowAtk_Damage
// 0x0004 (0x0004 - 0x0000)
struct GE_Player_Skia_ShadowAtk_Damage_C_ExecuteUbergraph_GE_Player_Skia_ShadowAtk_Damage final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

