#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Player_Fadia_UltraSkillMelee3_HitBack

#include "Basic.hpp"

#include "GE_SkillEffectBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Player_Fadia_UltraSkillMelee3_HitBack.GE_Player_Fadia_UltraSkillMelee3_HitBack_C
// 0x0000 (0x0C70 - 0x0C70)
class UGE_Player_Fadia_UltraSkillMelee3_HitBack_C final : public UGE_SkillEffectBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Player_Fadia_UltraSkillMelee3_HitBack_C">();
	}
	static class UGE_Player_Fadia_UltraSkillMelee3_HitBack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Player_Fadia_UltraSkillMelee3_HitBack_C>();
	}
};

}

