#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Reaction_GuangLingXiang_1009

#include "Basic.hpp"


namespace SDK::Params
{

// Function GE_Reaction_GuangLingXiang_1009.GE_Reaction_GuangLingXiang_1009_C.ExecuteUbergraph_GE_Reaction_GuangLingXiang_1009
// 0x0004 (0x0004 - 0x0000)
struct GE_Reaction_GuangLingXiang_1009_C_ExecuteUbergraph_GE_Reaction_GuangLingXiang_1009 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

