#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Skia_DamageBase

#include "Basic.hpp"

#include "GE_DamageBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Skia_DamageBase.GE_Skia_DamageBase_C
// 0x0000 (0x0C70 - 0x0C70)
class UGE_Skia_DamageBase_C : public UGE_DamageBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Skia_DamageBase_C">();
	}
	static class UGE_Skia_DamageBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Skia_DamageBase_C>();
	}
};

}

