#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTAnimSharingAdditiveInstance_mass_fs_BP

#include "Basic.hpp"

#include "HTAnimSharingAdditiveInstanceBaseBP_structs.hpp"


namespace SDK
{

// ScriptStruct HTAnimSharingAdditiveInstance_mass_fs_BP.HTAnimSharingAdditiveInstance_mass_fs_BP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0308 - 0x0308)
struct HTAnimSharingAdditiveInstance_mass_fs_BP::FAnimBlueprintGeneratedConstantData final : public HTAnimSharingAdditiveInstanceBaseBP::FAnimBlueprintGeneratedConstantData
{
};

}

