#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTPlayerSubVehicleAnim

#include "Basic.hpp"

#include "HTPlayerSubVehicleAnim_classes.hpp"
#include "HTPlayerSubVehicleAnim_parameters.hpp"


namespace SDK
{

// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UHTPlayerSubVehicleAnim_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "AnimGraph");

	Params::HTPlayerSubVehicleAnim_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.AnimNotify_GetOffOver
// (BlueprintCallable, BlueprintEvent)

void UHTPlayerSubVehicleAnim_C::AnimNotify_GetOffOver()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "AnimNotify_GetOffOver");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.AnimNotify_GetOnOver
// (BlueprintCallable, BlueprintEvent)

void UHTPlayerSubVehicleAnim_C::AnimNotify_GetOnOver()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "AnimNotify_GetOnOver");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHTPlayerSubVehicleAnim_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "BlueprintUpdateAnimation");

	Params::HTPlayerSubVehicleAnim_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.DriveLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        Param_DriveLayer                                       (Parm, OutParm, NoDestructor)

void UHTPlayerSubVehicleAnim_C::DriveLayer(struct FPoseLink* Param_DriveLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "DriveLayer");

	Params::HTPlayerSubVehicleAnim_C_DriveLayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_DriveLayer != nullptr)
		*Param_DriveLayer = std::move(Parms.Param_DriveLayer);
}


// Function HTPlayerSubVehicleAnim.HTPlayerSubVehicleAnim_C.ExecuteUbergraph_HTPlayerSubVehicleAnim
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHTPlayerSubVehicleAnim_C::ExecuteUbergraph_HTPlayerSubVehicleAnim(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HTPlayerSubVehicleAnim_C", "ExecuteUbergraph_HTPlayerSubVehicleAnim");

	Params::HTPlayerSubVehicleAnim_C_ExecuteUbergraph_HTPlayerSubVehicleAnim Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

