#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mon_025_BP

#include "Basic.hpp"

#include "Mon_025_BP_classes.hpp"
#include "Mon_025_BP_parameters.hpp"


namespace SDK
{

// Function mon_025_BP.mon_025_BP_C.Act06_2_Loc
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Act06_2_Loc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "Act06_2_Loc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.dead_hide
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Dead_hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "dead_hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.EndInto
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::EndInto()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "EndInto");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.ExecuteUbergraph_mon_025_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMon_025_BP_C::ExecuteUbergraph_mon_025_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "ExecuteUbergraph_mon_025_BP");

	Params::Mon_025_BP_C_ExecuteUbergraph_mon_025_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_025_BP.mon_025_BP_C.Hide_body
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Hide_body()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "Hide_body");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.NewFunction
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         NewRot                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMon_025_BP_C::NewFunction(struct FVector* NewParam, struct FRotator* NewRot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "NewFunction");

	Params::Mon_025_BP_C_NewFunction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);

	if (NewRot != nullptr)
		*NewRot = std::move(Parms.NewRot);
}


// Function mon_025_BP.mon_025_BP_C.OnBeginBattle
// (Event, Public, BlueprintEvent)

void AMon_025_BP_C::OnBeginBattle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "OnBeginBattle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.Open_body
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Open_body()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "Open_body");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMon_025_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.ResetBattle
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::ResetBattle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "ResetBattle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.RestCOL
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::RestCOL()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "RestCOL");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.Set_act06_2_loc
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Set_act06_2_loc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "Set_act06_2_loc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.Together_Act06_1
// (BlueprintCallable, BlueprintEvent)

void AMon_025_BP_C::Together_Act06_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "Together_Act06_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_0__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_0__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_1__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_1__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_2__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_2__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_2__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_2__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_3__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_3__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_3__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_3__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_3__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_3__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_4__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_4__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_4__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_4__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_4__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_4__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_5__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_5__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_5__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_5__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_5__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_5__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_6__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_6__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_6__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_6__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_6__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_6__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_7__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_7__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_7__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_7__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_7__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_7__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_8__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_8__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_8__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_8__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_8__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_8__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_9__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_9__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_9__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt_9__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t_9__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt_9__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt__FinishedFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_025_BP.mon_025_BP_C.öôt__UpdateFunc
// (BlueprintEvent)

void AMon_025_BP_C::__t__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_025_BP_C", "öôt__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

