#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mon_020_ControllerBP_World

#include "Basic.hpp"

#include "Mon_020_ControllerBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass mon_020_ControllerBP_World.mon_020_ControllerBP_World_C
// 0x0000 (0x0718 - 0x0718)
class AMon_020_ControllerBP_World_C final : public AMon_020_ControllerBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"mon_020_ControllerBP_World_C">();
	}
	static class AMon_020_ControllerBP_World_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMon_020_ControllerBP_World_C>();
	}
};

}

