#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mon_025_double_2_BP

#include "Basic.hpp"

#include "Mon_025_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass mon_025_double_2_BP.mon_025_double_2_BP_C
// 0x0000 (0x1FC0 - 0x1FC0)
class AMon_025_double_2_BP_C : public AMon_025_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"mon_025_double_2_BP_C">();
	}
	static class AMon_025_double_2_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMon_025_double_2_BP_C>();
	}
};

}

