#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Nanally_Aim_AnimLayer

#include "Basic.hpp"

#include "HTAimAnimLayerBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Nanally_Aim_AnimLayer.Nanally_Aim_AnimLayer_C
// 0x0000 (0x09B0 - 0x09B0)
class UNanally_Aim_AnimLayer_C final : public UHTAimAnimLayerBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Nanally_Aim_AnimLayer_C">();
	}
	static class UNanally_Aim_AnimLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNanally_Aim_AnimLayer_C>();
	}
};

}

