#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Nanally_Aim_AnimLayer

#include "Basic.hpp"

#include "HTAimAnimLayerBase_structs.hpp"


namespace SDK
{

// ScriptStruct Nanally_Aim_AnimLayer.Nanally_Aim_AnimLayer_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0448 - 0x0448)
struct Nanally_Aim_AnimLayer::FAnimBlueprintGeneratedConstantData final : public HTAimAnimLayerBase::FAnimBlueprintGeneratedConstantData
{
};

}

