#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_S038_Simple

#include "Basic.hpp"

#include "NPC_Sub_ml_Simple_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_S038_Simple.NPC_S038_Simple_C
// 0x0000 (0x0770 - 0x0770)
class ANPC_S038_Simple_C final : public ANPC_Sub_ml_Simple_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_S038_Simple_C">();
	}
	static class ANPC_S038_Simple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_S038_Simple_C>();
	}
};

}

