#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Physics_AnimLayer_lacrimosa

#include "Basic.hpp"

#include "Physics_AnimLayer_lacrimosa_classes.hpp"
#include "Physics_AnimLayer_lacrimosa_parameters.hpp"


namespace SDK
{

// Function Physics_AnimLayer_lacrimosa.Physics_AnimLayer_lacrimosa_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UPhysics_AnimLayer_lacrimosa_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Physics_AnimLayer_lacrimosa_C", "AnimGraph");

	Params::Physics_AnimLayer_lacrimosa_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function Physics_AnimLayer_lacrimosa.Physics_AnimLayer_lacrimosa_C.ExecuteUbergraph_Physics_AnimLayer_lacrimosa
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPhysics_AnimLayer_lacrimosa_C::ExecuteUbergraph_Physics_AnimLayer_lacrimosa(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Physics_AnimLayer_lacrimosa_C", "ExecuteUbergraph_Physics_AnimLayer_lacrimosa");

	Params::Physics_AnimLayer_lacrimosa_C_ExecuteUbergraph_Physics_AnimLayer_lacrimosa Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Physics_AnimLayer_lacrimosa.Physics_AnimLayer_lacrimosa_C.PhysicsAnimInterface
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_PhysicsAnimInterface                             (Parm, OutParm, NoDestructor)

void UPhysics_AnimLayer_lacrimosa_C::PhysicsAnimInterface(const struct FPoseLink& InPose, struct FPoseLink* Param_PhysicsAnimInterface)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Physics_AnimLayer_lacrimosa_C", "PhysicsAnimInterface");

	Params::Physics_AnimLayer_lacrimosa_C_PhysicsAnimInterface Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_PhysicsAnimInterface != nullptr)
		*Param_PhysicsAnimInterface = std::move(Parms.Param_PhysicsAnimInterface);
}

}

