#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Player_008_Skia_Shadow_AnimBP

#include "Basic.hpp"

#include "Player_008_Skia_Shadow_AnimBP_classes.hpp"
#include "Player_008_Skia_Shadow_AnimBP_parameters.hpp"


namespace SDK
{

// Function player_008_Skia_Shadow_AnimBP.player_008_Skia_Shadow_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UPlayer_008_Skia_Shadow_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_008_Skia_Shadow_AnimBP_C", "AnimGraph");

	Params::Player_008_Skia_Shadow_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function player_008_Skia_Shadow_AnimBP.player_008_Skia_Shadow_AnimBP_C.ExecuteUbergraph_player_008_Skia_Shadow_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayer_008_Skia_Shadow_AnimBP_C::ExecuteUbergraph_player_008_Skia_Shadow_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_008_Skia_Shadow_AnimBP_C", "ExecuteUbergraph_player_008_Skia_Shadow_AnimBP");

	Params::Player_008_Skia_Shadow_AnimBP_C_ExecuteUbergraph_player_008_Skia_Shadow_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

