#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Player_019_Mint

#include "Basic.hpp"


namespace SDK::Params
{

// Function Player_019_Mint.Player_019_Mint_C.ExecuteUbergraph_Player_019_Mint
// 0x0008 (0x0008 - 0x0000)
struct Player_019_Mint_C_ExecuteUbergraph_Player_019_Mint final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function Player_019_Mint.Player_019_Mint_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Player_019_Mint_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

