#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SLY_FunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SLY_FunctionLibrary.SLY_FunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class USLY_FunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void IsQuestBetween_SLY(class FName BeginQuest, class FName EndQuest, class UHTQuestComponent* QuestComponent, class UObject* __WorldContext, bool* IsInclude);
	static void PlayerTurnToActor(class AHTPlayerCharacter* HTPlayerCharacter, class AActor* TargetActor, const struct FVector& TargetLocation, class UObject* __WorldContext);
	static void SwapInt_SLY(int32 SwapA, int32 SwapB, class UObject* __WorldContext, int32* Aswap, int32* Bswap);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SLY_FunctionLibrary_C">();
	}
	static class USLY_FunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USLY_FunctionLibrary_C>();
	}
};

}

