#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TestLockRangeCommonAppear

#include "Basic.hpp"

#include "BP_PlayerType_LockBoxBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TestLockRangeCommonAppear.TestLockRangeCommonAppear_C
// 0x0000 (0x0148 - 0x0148)
class UTestLockRangeCommonAppear_C final : public UBP_PlayerType_LockBoxBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TestLockRangeCommonAppear_C">();
	}
	static class UTestLockRangeCommonAppear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTestLockRangeCommonAppear_C>();
	}
};

}

