#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Vehicle003_BackKit_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Vehicle003_BackKit_01.Vehicle003_BackKit_01_C
// 0x0010 (0x1090 - 0x1080)
class UVehicle003_BackKit_01_C final : public UHTVehicleSkeletalKitComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1080(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Vehicle003_BackKit_01(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Vehicle003_BackKit_01_C">();
	}
	static class UVehicle003_BackKit_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVehicle003_BackKit_01_C>();
	}
};

}

