#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_GamepadMainForm

#include "Basic.hpp"

#include "UINavigation_structs.hpp"
#include "Engine_structs.hpp"
#include "HTGame_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_GamepadMainForm.WB_GamepadMainForm_C
// 0x0008 (0x05A8 - 0x05A0)
class UWB_GamepadMainForm_C final : public UHTUI_GamepadMainForm
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnInputTypeChanged(EUINavigationInputType OldInputType, EUINavigationInputType NewInputType);
	void ExecuteUbergraph_WB_GamepadMainForm(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_GamepadMainForm_C">();
	}
	static class UWB_GamepadMainForm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_GamepadMainForm_C>();
	}
};

}

