#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Player_Fadia_AB

#include "Basic.hpp"

#include "Weapon_Player_Fadia_AB_classes.hpp"
#include "Weapon_Player_Fadia_AB_parameters.hpp"


namespace SDK
{

// Function Weapon_Player_Fadia_AB.Weapon_Player_Fadia_AB_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UWeapon_Player_Fadia_AB_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Weapon_Player_Fadia_AB_C", "AnimGraph");

	Params::Weapon_Player_Fadia_AB_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function Weapon_Player_Fadia_AB.Weapon_Player_Fadia_AB_C.ExecuteUbergraph_Weapon_Player_Fadia_AB
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWeapon_Player_Fadia_AB_C::ExecuteUbergraph_Weapon_Player_Fadia_AB(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Weapon_Player_Fadia_AB_C", "ExecuteUbergraph_Weapon_Player_Fadia_AB");

	Params::Weapon_Player_Fadia_AB_C_ExecuteUbergraph_Weapon_Player_Fadia_AB Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

