#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero09_VinesIK_AnimLayer

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function 009_VinesIK_AnimLayer.009_VinesIK_AnimLayer_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct Zero09_VinesIK_AnimLayer_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

// Function 009_VinesIK_AnimLayer.009_VinesIK_AnimLayer_C.ExecuteUbergraph_009_VinesIK_AnimLayer
// 0x0004 (0x0004 - 0x0000)
struct Zero09_VinesIK_AnimLayer_C_ExecuteUbergraph_009_VinesIK_AnimLayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function 009_VinesIK_AnimLayer.009_VinesIK_AnimLayer_C.VinesIKAnimationLayer
// 0x0020 (0x0020 - 0x0000)
struct Zero09_VinesIK_AnimLayer_C_VinesIKAnimationLayer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              Param_VinesIKAnimationLayer;                       // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

}

